#!/bin/bash -e

# "script/bootstrap is used solely for fulfilling dependencies of the project."
#    -- scripts-to-rule-them-all

# In this case, the dependencies are the other services, so this
# script runs script/setup for all the other services.


cd "$(dirname "${0}")/.."
eval "$(cat services.ini  | ./ini_parser.py)"
cd services
top=$(pwd)

# Install Python dependencies
pipenv --python 3.6
pipenv install --dev

mkdir -p log


if type gem > /dev/null; then
  gem install foreman
else
  echo "Please install ruby and rubygems! This requires foreman to manage processes."
fi

for repo in ${SERVICES[@]}; do
    IFS="@"
    set $repo
    service=$1
    version=$2

    cd $top
    echo "Cloning $service at $version"
    curl -sSL https://github.com/dod-ccpo/$service/archive/$version.tar.gz | tar xz
    mv $service-$version $service
    # "script/setup is typically run after an initial clone"
    cd $top/$service
    log=$top/log/$service.setup.log
    if [ -n "${ATAT_STACK_VERBOSE+set}" ]; then
      echo -e "\tscript/setup: Starting output for $service";
      script/setup
    else
      echo -e "\tscript/setup: Output at $log";
      script/setup > $log 2>&1 || echo "⚠️  Setup failed for $service"
    fi
done
