#!/bin/bash -e

# "script/bootstrap is used solely for fulfilling dependencies of the project."
#    -- scripts-to-rule-them-all

# In this case, the dependencies are the other services, so this
# script runs script/setup for all the other services.


cd "$(dirname "${0}")/.."
eval "$(cat services.ini  | ./ini_parser.py)"
cd services
top=$(pwd)

mkdir -p log

for repo in ${SERVICES[@]}; do
    IFS="@"
    set $repo
    service=$1
    version=$2

    cd $top
    echo "Cloning $service at $version"
    curl -sSL https://github.com/dod-ccpo/$service/archive/$version.tar.gz | tar xz
    mv $service-$version $service
    # "script/setup is typically run after an initial clone"
    cd $top/$service
    log=$top/log/$service.setup.log
    echo -e "\tscript/setup: Output at $log";
    script/setup > $log 2>&1 || echo "⚠️  Setup failed for $service"
done
