#!/bin/bash -e

# "script/setup is typically run after an initial clone, or to
# reset the project to its initial state."
#    -- scripts-to-rule-them-all

cd $(dirname $0)/..

rm -rf services/*

script/bootstrap
