#!/bin/bash -e

cd $(dirname $0)/..
source services.ini
cd services
top=$(pwd)
mkdir -p log
i=1
for service in $SERVICES; do
    cd $top/$service
    log=$top/log/$service.test.log
    echo "# testing $service"
    if script/test > $log 2>&1; then
        echo "ok $i - $service"
    else
        echo "not ok $i - $service"
        echo "# See $log"
    fi
    i=$(expr $i + 1)
done

