#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Run unit tests
if ! curl -s --fail http://localhost:8000 > /dev/null; then
  echo "Make sure you're running the server before running tests!"
  exit
fi
pipenv run python -m pytest -s $*

