#!/bin/bash -e

cd $(dirname $0)/..
eval "$(cat services.ini  | ./ini_parser.py)"
cd services
top=$(pwd)
mkdir -p log
i=1
for service in ${SERVICE_NAMES[@]}; do
    cd $top/$service
    log=$top/log/$service.test.log
    echo "# testing $service"
    if script/test > $log 2>&1; then
        echo "ok $i - $service"
    else
        echo "not ok $i - $service"
        echo "# See $log"
    fi
    i=$(expr $i + 1)
done

